theme: jekyll-theme-architect

title: "Jiangyu Lan"           # 网站标题
description: "Lan's HomePage"  # 网站描述
avatar: "/assets/avatar.jpg" # 头像路径
navigation:
  - name: "博客"           # 导航菜单项
    url: "/blog/"
  - name: "项目"
    url: "/projects/"
