theme: jekyll-theme-architect

title: "Jiangyu Lan"
description: "Academic homepage of Jiangyu Lan"
navigation:
  - name: "Blog / 博客"
    url: "/blog/"
  - name: "Projects / 项目"
    url: "/projects/"
